apiVersion: v1
kind: ServiceAccount
metadata:
  name: gardener-slacker
  namespace: monitoring
  labels:
    app: gardener
    role: metrics-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gardener-slacker
rules:
- apiGroups:
  - core.gardener.cloud
  resources:
  - shoots
  - projects
  - seeds
  - plants
  verbs:
  - get
  - watch
  - list
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gardener-slacker
subjects:
- kind: ServiceAccount
  name: gardener-slacker
  namespace: monitoring
roleRef:
  kind: ClusterRole
  name: gardener-slacker
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: gardener-slacker
  name: gardener-slacker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gardener-slacker
  serviceName: gardener-slacker
  template:
    metadata:
      labels:
        app: gardener-slacker
        name: gardener-slacker
    spec:
      containers:
      - name: gardener-slacker
        image: mwennrich/gardener-slacker:latest
        command:
        - /gardener-slacker
        - --filename=/data/db.json
        - --slackurl=<slack-url>
        - --kubeconfig=/etc/seed/kubecfg.yaml
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /etc/seed
          name: seed-kubecfg
          readOnly: true
      serviceAccount: gardener-slacker
      serviceAccountName: gardener-slacker
      volumes:
      - name: seed-kubecfg
        secret:
          defaultMode: 420
          secretName: seed-kubecfg
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Mi
      volumeMode: Filesystem
